version: '3.8'

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.7.1
    ports:
      - "8086:8086"
      - 25826:25826/udp
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=jmeter
      - DOCKER_INFLUXDB_INIT_PASSWORD=jmeterpassword
      - DOCKER_INFLUXDB_INIT_ORG=MainOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION_POLICY=autogen
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    command: >
      influx setup \
        --host http://localhost:8086 \
        --token my-secret-token \
        --org MainOrg \
        --bucket jmeter_bucket \
        --username jmeter \
        --password jmeterpassword \
        --retention 0 --retention-autogen 0
    networks:tooi 
      - jmeter-net

  grafana:
    image: grafana/grafana:10.1  # Sử dụng phiên bản Grafana 10.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - grafana.env
    networks:
      - jmeter-net
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:

networks:
  jmeter-net:
    driver: bridge

